ALTER TABLE "ETransportNoticeItem"
ADD COLUMN IF NOT EXISTS "netWeightPerUnitKg" DECIMAL(65,30) NOT NULL DEFAULT 0;

ALTER TABLE "ETransportNoticeItem"
ADD COLUMN IF NOT EXISTS "netWeightTotalKg" DECIMAL(65,30) NOT NULL DEFAULT 0;
