services:
  - type: web
    name: poshard-frontend
    env: static
    plan: starter
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
