ALTER TABLE "SalesInvoice"
ADD COLUMN "totalDiscountFc" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "totalDiscountRon" DECIMAL(65,30) NOT NULL DEFAULT 0;

ALTER TABLE "SalesInvoiceItem"
ADD COLUMN "discountPercent" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "discountAmountFc" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN "discountAmountRon" DECIMAL(65,30) NOT NULL DEFAULT 0;
