import { useEffect, useState } from "react"
import { Building2, Save } from "lucide-react"
import { api } from "../../lib/api"

type Profile = { name: string; cui: string; regNo: string; address: string; city: string; county: string; country: string; iban: string; bank: string; email: string; phone: string; invoiceSeries: string }
const empty: Profile = { name: "", cui: "", regNo: "", address: "", city: "", county: "", country: "Romania", iban: "", bank: "", email: "", phone: "", invoiceSeries: "GUF" }

export default function ControlPanelBillingProfile() {
  const [form, setForm] = useState<Profile>(empty)
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState("")
  const [error, setError] = useState("")
  useEffect(() => { void api<{ item?: Partial<Profile> | null }>("/api/v1/admin/platform/billing-profile").then((data) => setForm({ ...empty, ...(data.item || {}) })).catch((err) => setError(err.message || "Nu am putut încărca profilul.")) }, [])
  const set = (key: keyof Profile, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function save() { try { setSaving(true); setError(""); await api("/api/v1/admin/platform/billing-profile", { method: "PUT", body: JSON.stringify(form) }); setMessage("Datele emitentului au fost salvate.") } catch (err: any) { setError(err.message || "Nu am putut salva datele.") } finally { setSaving(false) } }
  return <div className="space-y-4"><section className="border border-[#2b2c33] bg-[#34353d] px-4 py-4 text-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[#f0ad3d]"><Building2 size={14} />Facturare / Date emitent</div><h1 className="mt-1 text-2xl font-semibold">Firma ta de developer</h1><p className="mt-1 text-sm text-slate-300">Aceste date apar ca emitent pe facturile de abonament Gufo.</p></div><button onClick={save} disabled={saving || !form.name.trim()} className="inline-flex items-center gap-2 bg-[#f39c12] px-4 py-2 text-sm font-bold text-slate-950 disabled:opacity-60"><Save size={15} />{saving ? "Se salvează..." : "Salvează"}</button></div></section>{error ? <div className="border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div> : null}{message ? <div className="border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div> : null}<section className="border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-4 md:grid-cols-2"><label className="md:col-span-2"><span className="text-xs font-bold text-slate-600">Denumire firmă *</span><input value={form.name} onChange={(e) => set("name", e.target.value)} className="mt-1 w-full border border-slate-200 px-3 py-2 text-sm" /></label>{([['cui','CUI'],['regNo','Reg. Com.'],['invoiceSeries','Serie facturi'],['phone','Telefon'],['email','Email'],['bank','Bancă'],['iban','IBAN'],['city','Localitate'],['county','Județ'],['country','Țară']] as Array<[keyof Profile,string]>).map(([key,label]) => <label key={key}><span className="text-xs font-bold text-slate-600">{label}</span><input value={form[key]} onChange={(e) => set(key,e.target.value)} className="mt-1 w-full border border-slate-200 px-3 py-2 text-sm" /></label>)}<label className="md:col-span-2"><span className="text-xs font-bold text-slate-600">Adresă sediu</span><input value={form.address} onChange={(e) => set("address",e.target.value)} className="mt-1 w-full border border-slate-200 px-3 py-2 text-sm" /></label></div></section></div>
}
